import jsPDF from 'jspdf';

function addHeader(doc, title) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(92, 124, 250);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SATURN QA Agent', 14, 15);
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 14, 23);
  doc.setTextColor(30, 41, 59);
}

function addFooter(doc, pageNum) {
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by SATURN QA Agent  •  Page ${pageNum}`, 14, 290);
  doc.text(new Date().toLocaleDateString(), 170, 290);
}

function checkPageBreak(doc, y, needed = 20) {
  if (y + needed > 275) {
    doc.addPage();
    return 40;
  }
  return y;
}

export function exportTestCasesPDF(data) {
  const doc = new jsPDF();
  addHeader(doc, 'Test Case Report');
  let y = 40;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Requirement:', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const reqLines = doc.splitTextToSize(data.requirement || 'N/A', 180);
  doc.text(reqLines, 14, y);
  y += reqLines.length * 5 + 10;

  const sections = [
    { title: 'Test Scenarios', items: data.scenarios, type: 'scenario' },
    { title: 'Positive Test Cases', items: data.positiveCases, type: 'case' },
    { title: 'Negative Test Cases', items: data.negativeCases, type: 'case' },
    { title: 'Edge Cases', items: data.edgeCases, type: 'case' },
  ];

  for (const section of sections) {
    y = checkPageBreak(doc, y, 15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(92, 124, 250);
    doc.text(section.title, 14, y);
    y += 8;
    doc.setTextColor(30, 41, 59);

    for (const item of section.items || []) {
      y = checkPageBreak(doc, y, 30);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(`${item.id}: ${item.title}`, 14, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);

      if (section.type === 'scenario') {
        const desc = doc.splitTextToSize(item.description || '', 175);
        doc.text(desc, 18, y);
        y += desc.length * 4 + 4;
      } else {
        if (item.preconditions) {
          doc.text(`Preconditions: ${item.preconditions}`, 18, y);
          y += 5;
        }
        if (item.steps) {
          doc.text('Steps:', 18, y);
          y += 4;
          item.steps.forEach((step, i) => {
            y = checkPageBreak(doc, y);
            doc.text(`  ${i + 1}. ${step}`, 22, y);
            y += 4;
          });
        }
        if (item.expectedResult) {
          y = checkPageBreak(doc, y);
          doc.text(`Expected: ${item.expectedResult}`, 18, y);
          y += 5;
        }
        if (item.priority) {
          doc.text(`Priority: ${item.priority}`, 18, y);
          y += 5;
        }
        y += 3;
      }
    }
    y += 5;
  }

  addFooter(doc, 1);
  doc.save('saturn-test-cases.pdf');
}

export function exportBugReportPDF(data) {
  const doc = new jsPDF();
  addHeader(doc, 'Bug Report');
  let y = 40;

  const fields = [
    ['Bug ID', data.bugId],
    ['Summary', data.summary],
    ['Severity', data.severity],
    ['Priority', data.priority],
  ];

  doc.setFontSize(10);
  for (const [label, value] of fields) {
    y = checkPageBreak(doc, y);
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 14, y);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(String(value || 'N/A'), 140);
    doc.text(lines, 50, y);
    y += Math.max(lines.length * 5, 6) + 2;
  }

  if (data.environment) {
    y = checkPageBreak(doc, y, 20);
    doc.setFont('helvetica', 'bold');
    doc.text('Environment:', 14, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    for (const [key, val] of Object.entries(data.environment)) {
      doc.text(`  ${key}: ${val}`, 18, y);
      y += 5;
    }
    y += 3;
  }

  y = checkPageBreak(doc, y, 20);
  doc.setFont('helvetica', 'bold');
  doc.text('Steps to Reproduce:', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  (data.stepsToReproduce || []).forEach((step, i) => {
    y = checkPageBreak(doc, y);
    doc.text(`${i + 1}. ${step}`, 18, y);
    y += 5;
  });

  for (const [label, key] of [
    ['Expected Result', 'expectedResult'],
    ['Actual Result', 'actualResult'],
    ['Additional Notes', 'additionalNotes'],
  ]) {
    if (data[key]) {
      y = checkPageBreak(doc, y, 15);
      doc.setFont('helvetica', 'bold');
      doc.text(`${label}:`, 14, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(data[key], 175);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 4;
    }
  }

  addFooter(doc, 1);
  doc.save(`saturn-bug-${data.bugId || 'report'}.pdf`);
}

export function exportTestDataPDF(data) {
  const doc = new jsPDF();
  addHeader(doc, 'Test Data Report');
  let y = 40;

  doc.setFontSize(10);
  doc.text(`Data Type: ${data.dataType}  |  Count: ${data.count}`, 14, y);
  y += 12;

  const records = data.records || [];
  const keys = records.length > 0 ? Object.keys(records[0]).filter((k) => k !== 'id') : [];

  for (const record of records) {
    y = checkPageBreak(doc, y, 30);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(92, 124, 250);
    doc.text(`Record #${record.id}`, 14, y);
    y += 6;
    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'normal');

    for (const key of keys) {
      y = checkPageBreak(doc, y);
      doc.setFont('helvetica', 'bold');
      doc.text(`${key}:`, 18, y);
      doc.setFont('helvetica', 'normal');
      doc.text(String(record[key] || ''), 55, y);
      y += 5;
    }
    y += 4;
  }

  addFooter(doc, 1);
  doc.save('saturn-test-data.pdf');
}
